/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

<<<<<<< HEAD


import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import netbeans.Administracao;
import netbeans.Venda;
import netbeans.ListaVendas;

=======
import dao.VendaDAO;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import netbeans.Venda;
import dao.VendaDAO;
>>>>>>> e9ad854 (Integração do banco de dados)

/**
 *
 * @author butuk
 */
public class RelatorioComprasAdministracao extends javax.swing.JFrame {

<<<<<<< HEAD
private final String[] tableColumns = {"Cliente", "Data", "Item", "Preço"};

DefaultTableModel tableModel = new DefaultTableModel(tableColumns, 0);

Administracao admin = new Administracao();

List<Venda> listaVendas = ListaVendas.listarVendas();
    
    public RelatorioComprasAdministracao() {
        initComponents();
=======
    public void preencherTabela(List<Venda> vendas){
        String colunas[] = {"Id", "Cliente", "Data", "Item", "Preço"};
        String dados[][] = new String[vendas.size()][colunas.length];
        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        int i = 0;
        for(Venda v : vendas){
            dados[i] = new String[]{
                String.valueOf(v.getId()),
                v.getCliente().getNome(),
                v.getData().format(formatter),
                v.getComputador().getNome(),
                String.valueOf(v.getComputador().getPreco())
            };
            i++;
        }
        
        DefaultTableModel model = new DefaultTableModel(dados, colunas);
        tblVenda.setModel(model);
    }
    
    public RelatorioComprasAdministracao() {
        initComponents();
        String dataIni = txtDataInicial.getText();
        String dataFinal = txtDataFinal.getText();
        VendaDAO dao = new VendaDAO();
        
        preencherTabela(dao.listarTodasVendas());
        
>>>>>>> e9ad854 (Integração do banco de dados)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
<<<<<<< HEAD
=======
        jLabel2 = new javax.swing.JLabel();
        txtDataInicial = new javax.swing.JTextField();
        txtDataFinal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
>>>>>>> e9ad854 (Integração do banco de dados)
        btnVoltar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        bntExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
<<<<<<< HEAD
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVendas = new javax.swing.JTable();
=======
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVenda = new javax.swing.JTable();
>>>>>>> e9ad854 (Integração do banco de dados)

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("System Select - Gerenciador de Vendas");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SYSYEM SELECT");

<<<<<<< HEAD
=======
        jLabel2.setText("Pesquisar por data:");

        txtDataInicial.setToolTipText("Informe a data Inicial (ex: 10/02/2024)");
        txtDataInicial.setNextFocusableComponent(txtDataFinal);
        txtDataInicial.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtDataInicialCaretUpdate(evt);
            }
        });

        txtDataFinal.setToolTipText("Informe a data final (ex: 15/06/2024)");
        txtDataFinal.setNextFocusableComponent(btnPesquisar);
        txtDataFinal.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtDataFinalCaretUpdate(evt);
            }
        });

        jLabel3.setText("a");

        btnPesquisar.setBackground(new java.awt.Color(0, 102, 204));
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setToolTipText("Consultar todas as datas entre os intervalos informados");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

>>>>>>> e9ad854 (Integração do banco de dados)
        btnVoltar.setText("< Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(0, 102, 204));
        btnCadastrar.setText("Cadastrar Venda");
        btnCadastrar.setToolTipText("Cadastrar uma venda");
<<<<<<< HEAD
        btnCadastrar.setNextFocusableComponent(btnEditar);
=======
>>>>>>> e9ad854 (Integração do banco de dados)
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        bntExcluir.setBackground(new java.awt.Color(153, 0, 51));
        bntExcluir.setText("Excluir Venda");
<<<<<<< HEAD
        bntExcluir.setToolTipText("Excluir a venda selecionada");
=======
        bntExcluir.setToolTipText("Excluir uma venda");
>>>>>>> e9ad854 (Integração do banco de dados)
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar Venda");
<<<<<<< HEAD
        btnEditar.setToolTipText("Editar a venda selecionada");
        btnEditar.setNextFocusableComponent(bntExcluir);
=======
        btnEditar.setToolTipText("Editar uma venda");
>>>>>>> e9ad854 (Integração do banco de dados)
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel4.setText("Gerenciador de Vendas");

<<<<<<< HEAD
=======
        btnLimpar.setText("Limpar");
        btnLimpar.setToolTipText("Limpar filtros");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

>>>>>>> e9ad854 (Integração do banco de dados)
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(bntExcluir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
<<<<<<< HEAD
                        .addComponent(btnVoltar)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(jLabel1)))
                        .addContainerGap(249, Short.MAX_VALUE))))
=======
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimpar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnVoltar)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(207, 207, 207)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(197, 197, 197)
                                        .addComponent(jLabel1)))))
                        .addContainerGap(147, Short.MAX_VALUE))))
>>>>>>> e9ad854 (Integração do banco de dados)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnVoltar))
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
<<<<<<< HEAD
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
=======
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnPesquisar)
                    .addComponent(btnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
>>>>>>> e9ad854 (Integração do banco de dados)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(bntExcluir)
                    .addComponent(btnEditar)))
        );

<<<<<<< HEAD
        String[] colunas = {"Cliente", "Data", "Item", "Preço"};
        DefaultTableModel tabelaModelo = new DefaultTableModel(colunas, 0);

        Administracao admin = new Administracao();

        List<Venda> listaCompleta = ListaVendas.listarVendas();

        for(int i = 0; i < listaCompleta.size(); i++){
            Venda vendaAtual = listaCompleta.get(i);

            String[] linha ={
                vendaAtual.getUsuario().getNome(),
                vendaAtual.getDataVenda(),
                vendaAtual.getComputador().getNome(),
                String.valueOf(vendaAtual.getComputador().getPreco())
            };

            tabelaModelo.addRow(linha);
        }
        tblVendas.setModel(tabelaModelo);
        jScrollPane1.setViewportView(tblVendas);
=======
        tblVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cliente", "Data", "Item", "Preço"
            }
        ));
        jScrollPane1.setViewportView(tblVenda);
>>>>>>> e9ad854 (Integração do banco de dados)

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
=======
    private void txtDataInicialCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDataInicialCaretUpdate

    }//GEN-LAST:event_txtDataInicialCaretUpdate

    private void txtDataFinalCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDataFinalCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataFinalCaretUpdate

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        String dataInicial = txtDataInicial.getText();
        String dataFinal = txtDataFinal.getText();
        
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    LocalDateTime dataHoraInicial = null;
    LocalDateTime dataHoraFinal = null;

    try {
        if (!dataInicial.isEmpty()) {
            dataHoraInicial = LocalDate.parse(dataInicial, dateFormatter).atStartOfDay();
        }
        if (!dataFinal.isEmpty()) {
            dataHoraFinal = LocalDate.parse(dataFinal, dateFormatter).atTime(23, 59, 59);
        }
    } catch (DateTimeParseException e) {
        JOptionPane.showMessageDialog(this, "Formato de data inválido! Use o formato dd/MM/yyyy.");
        return;
    }
        
        VendaDAO dao = new VendaDAO();
        List<Venda> vendas = dao.listarTodasVendasData(dataHoraInicial, dataHoraFinal);
        preencherTabela(vendas);
    }//GEN-LAST:event_btnPesquisarActionPerformed

>>>>>>> e9ad854 (Integração do banco de dados)
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaPrincipalAdministracao telaPrincipal = new TelaPrincipalAdministracao();
        telaPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
<<<<<<< HEAD
        Administracao admin = new Administracao();
        int vendaSelecionada = tblVendas.getSelectedRow();
        
        if(vendaSelecionada != -1){
            
            Venda vendaEncontrada = admin.encontrarVenda(vendaSelecionada);
            
            EdicaoVenda telaEdicao = new EdicaoVenda(vendaEncontrada, vendaSelecionada);
=======
        int vendaSelecionada = tblVenda.getSelectedRow();
        
        VendaDAO dao = new VendaDAO();
        
        if(vendaSelecionada != -1){
            int idVenda = Integer.parseInt(tblVenda.getValueAt(vendaSelecionada, 0).toString());
            
            Venda vendaEncontrada = dao.encontrarVenda(idVenda);
            
            EdicaoVenda telaEdicao = new EdicaoVenda(vendaEncontrada);
>>>>>>> e9ad854 (Integração do banco de dados)
            telaEdicao.setVisible(true);
            dispose();
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Selecione uma venda para editar.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
    CadastroVenda telaCadastro = new CadastroVenda();
    telaCadastro.setVisible(true);
    dispose();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
<<<<<<< HEAD

        
        Administracao admin = new Administracao();
        int vendaSelecionada = tblVendas.getSelectedRow();
        if(vendaSelecionada != -1){

        int confirmacao = JOptionPane.showConfirmDialog(null, "Tem certeza que excluir a venda selecionado?", "Excluir Dados?", JOptionPane.YES_NO_OPTION);
                
        if(confirmacao == JOptionPane.YES_OPTION){
            admin.removerVenda(vendaSelecionada);
            JOptionPane.showMessageDialog(null, "Venda excluída com sucesso.");
            atualizarLista();
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Operação Cancelada.");
        }

        }
        
        else{
            JOptionPane.showMessageDialog(null, "Selecione uma venda para excluir.");
        }

    }//GEN-LAST:event_bntExcluirActionPerformed

=======
        VendaDAO dao = new VendaDAO();
        int vendaSelecionada = tblVenda.getSelectedRow();
        if(vendaSelecionada != -1){
            int idVenda = Integer.parseInt(tblVenda.getValueAt(vendaSelecionada, 0).toString());
            dao.excluirVenda(idVenda);
            JOptionPane.showMessageDialog(null, "Venda excluída com sucesso.");
            List<Venda> vendas = dao.listarTodasVendas();
            preencherTabela(vendas);
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione uma venda para excluir.");
        }
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtDataInicial.setText("");
        txtDataFinal.setText("");
        VendaDAO dao = new VendaDAO();
        List<Venda> vendas = dao.listarTodasVendas();
        preencherTabela(vendas);
    }//GEN-LAST:event_btnLimparActionPerformed

>>>>>>> e9ad854 (Integração do banco de dados)
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioComprasUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioComprasUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioComprasUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioComprasUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioComprasUsuarios().setVisible(true);
            }
        });
    }
<<<<<<< HEAD
    
    public void atualizarLista(){
        if(!listaVendas.isEmpty()){
        Venda venda;
        
        tableModel = new DefaultTableModel(tableColumns, 0);
        
        for(int i = 0; i < listaVendas.size(); i++){
            venda = listaVendas.get(i);
            
            String[] rowData = {venda.getUsuario().getNome(), venda.getDataVenda(), venda.getComputador().getNome(), String.valueOf(venda.getComputador().getPreco())};
        
        tableModel.addRow(rowData);
        }
        
        tblVendas.setModel(tableModel);    
    }
    else{
        tableModel = new DefaultTableModel(tableColumns, 0);
        tblVendas.setModel(tableModel);
    }
    }
=======
>>>>>>> e9ad854 (Integração do banco de dados)

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditar;
<<<<<<< HEAD
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVendas;
=======
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVenda;
    private javax.swing.JTextField txtDataFinal;
    private javax.swing.JTextField txtDataInicial;
>>>>>>> e9ad854 (Integração do banco de dados)
    // End of variables declaration//GEN-END:variables
}
