/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

<<<<<<< HEAD
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import netbeans.Administracao;
import netbeans.Computador;
import netbeans.ListaComputadores;
=======
import dao.ComputadorDAO;
import dao.UsuarioDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import netbeans.Computador;
>>>>>>> e9ad854 (Integração do banco de dados)

/**
 *
 * @author butuk
 */
public class RelatorioEstoque extends javax.swing.JFrame {

<<<<<<< HEAD
    private final String[] tableColumns = {"Nome", "Marca", "Tipo", "Preço", "Quantidade"};
    
    DefaultTableModel tableModel = new DefaultTableModel(tableColumns, 0);
    
    Administracao admin = new Administracao();
    
    List<Computador> listaComputadores = ListaComputadores.listarComputadores();
    
    
    public RelatorioEstoque() {
        initComponents();
=======
    public void preencherTabela(List<Computador> computadores){
        String colunas[] = {"Id", "Nome", "Descrição", "Tipo", "Marca", "Preço", "Quantidade"};
        String dados[][] = new String[computadores.size()][colunas.length];
        
        int i = 0;
        for(Computador c : computadores){
            dados[i] = new String[]{
                String.valueOf(c.getId()),
                c.getNome(),
                c.getDescricao(),
                c.getTipo(),
                c.getMarca(),
                String.valueOf(c.getPreco()),
                String.valueOf(c.getQuantidade())
            };
            
            i++;
        }

    DefaultTableModel model = new DefaultTableModel(dados, colunas);
    tblItem.setModel(model);
    }
    
    public RelatorioEstoque() {
        initComponents();
        String nome = txtNome.getText();
        String marca = txtMarca.getText();
        String precoInicial = txtValorIni.getText();
        String precoFinal = txtValorFinal.getText();
        
        ComputadorDAO dao = new ComputadorDAO();
        
        List<Computador> listaComputadores = dao.listar(nome, marca, precoInicial, precoFinal);
        preencherTabela(listaComputadores);
        
>>>>>>> e9ad854 (Integração do banco de dados)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
<<<<<<< HEAD
        bntCadastrar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblComputadores = new javax.swing.JTable();
=======
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        bntCadastrar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtValorIni = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtValorFinal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
>>>>>>> e9ad854 (Integração do banco de dados)

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("System Select - Gerenciar Estoque");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SYSTEM SELECT");

<<<<<<< HEAD
=======
        jLabel2.setText("Pesquisar por Nome:");

        txtNome.setToolTipText("Informe o nome do produto");
        txtNome.setNextFocusableComponent(txtMarca);
        txtNome.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNomeCaretUpdate(evt);
            }
        });

>>>>>>> e9ad854 (Integração do banco de dados)
        bntCadastrar.setBackground(new java.awt.Color(0, 102, 204));
        bntCadastrar.setText("Cadastrar Item");
        bntCadastrar.setToolTipText("Cadastrar um item");
        bntCadastrar.setNextFocusableComponent(btnEditar);
        bntCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCadastrarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(204, 0, 51));
        btnExcluir.setText("Excluir Item");
<<<<<<< HEAD
        btnExcluir.setToolTipText("Excluir o item selecionado");
=======
        btnExcluir.setToolTipText("Excluir item selecionado");
>>>>>>> e9ad854 (Integração do banco de dados)
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar Item");
        btnEditar.setToolTipText("Editar o item selecionado");
        btnEditar.setNextFocusableComponent(btnExcluir);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

<<<<<<< HEAD
=======
        jLabel3.setText("Pesquisar por Marca:");

        txtMarca.setToolTipText("Informe a marca do produto");
        txtMarca.setNextFocusableComponent(txtValorIni);
        txtMarca.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtMarcaCaretUpdate(evt);
            }
        });

>>>>>>> e9ad854 (Integração do banco de dados)
        btnVoltar.setText("< Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

<<<<<<< HEAD
=======
        jLabel4.setText("Pesquisar entre preços:");

        txtValorIni.setToolTipText("Informe o valor mínimo");
        txtValorIni.setNextFocusableComponent(txtValorFinal);
        txtValorIni.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtValorIniCaretUpdate(evt);
            }
        });

        jLabel5.setText("a");

        txtValorFinal.setToolTipText("Informe o valor máximo");
        txtValorFinal.setNextFocusableComponent(bntCadastrar);
        txtValorFinal.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtValorFinalCaretUpdate(evt);
            }
        });

>>>>>>> e9ad854 (Integração do banco de dados)
        jLabel6.setText("Gerenciar Estoque");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 306, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(382, 382, 382))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(407, 407, 407))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
<<<<<<< HEAD
                .addComponent(bntCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addGap(17, 17, 17)
                .addComponent(btnExcluir)
=======
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bntCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar)
                        .addGap(17, 17, 17)
                        .addComponent(btnExcluir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(91, 91, 91)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorIni, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
>>>>>>> e9ad854 (Integração do banco de dados)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnVoltar))
                .addGap(1, 1, 1)
                .addComponent(jLabel6)
<<<<<<< HEAD
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
=======
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtValorIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
>>>>>>> e9ad854 (Integração do banco de dados)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntCadastrar)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar))
                .addContainerGap())
        );

<<<<<<< HEAD
        String[] colunas = {"Nome", "Marca", "Tipo", "Preço", "Quantidade"};
        DefaultTableModel tabelaModelo = new DefaultTableModel(colunas, 0);

        Administracao admin = new Administracao();

        List<Computador> listaCompleta = ListaComputadores.listarComputadores();

        for(int i = 0; i < listaCompleta.size(); i++){
            Computador computadorAtual = listaCompleta.get(i);

            String[] linha ={
                computadorAtual.getNome(),
                computadorAtual.getMarca(),
                computadorAtual.getTipo(),
                String.valueOf(computadorAtual.getPreco()),
                String.valueOf(computadorAtual.getQuantidade())
            };

            tabelaModelo.addRow(linha);
        }
        tblComputadores.setModel(tabelaModelo);
        jScrollPane1.setViewportView(tblComputadores);
=======
        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Descrição", "Tipo", "Marca", "Preço", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(tblItem);
>>>>>>> e9ad854 (Integração do banco de dados)

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
 
        Administracao admin = new Administracao();
        
        int itemSelecionado = tblComputadores.getSelectedRow();
        if(itemSelecionado != -1){
        int confirmacao = JOptionPane.showConfirmDialog(null, "Tem certeza que excluir o item selecionado?", "Excluir Dados?", JOptionPane.YES_NO_OPTION);
                
        if(confirmacao == JOptionPane.YES_OPTION){
        
            String nomeItem = tblComputadores.getValueAt(itemSelecionado, 0).toString();
            admin.removerComputador(nomeItem);
            JOptionPane.showMessageDialog(null, "Item excluído com sucesso.");
            atualizarLista();
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Operação Cancelada.");
        }
}
        else{
            JOptionPane.showMessageDialog(null, "Selecione um item para excluir.");
        }

=======
    private void txtNomeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNomeCaretUpdate
        String nome = txtNome.getText();
        String marca = txtMarca.getText();
        String precoInicial = txtValorIni.getText();
        String precoFinal = txtValorFinal.getText();
        
        ComputadorDAO dao = new ComputadorDAO();
        
        List<Computador> listaComputadores = dao.listar(nome, marca, precoInicial, precoFinal);
        preencherTabela(listaComputadores);
    }//GEN-LAST:event_txtNomeCaretUpdate

    private void txtMarcaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtMarcaCaretUpdate
        String nome = txtNome.getText();
        String marca = txtMarca.getText();
        String precoInicial = txtValorIni.getText();
        String precoFinal = txtValorFinal.getText();
        
        ComputadorDAO dao = new ComputadorDAO();
        
        List<Computador> listaComputadores = dao.listar(nome, marca, precoInicial, precoFinal);
        preencherTabela(listaComputadores);
    }//GEN-LAST:event_txtMarcaCaretUpdate

    private void txtValorIniCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtValorIniCaretUpdate
        String nome = txtNome.getText();
        String marca = txtMarca.getText();
        String precoInicial = txtValorIni.getText();
        String precoFinal = txtValorFinal.getText();
        
        ComputadorDAO dao = new ComputadorDAO();
        
        List<Computador> listaComputadores = dao.listar(nome, marca, precoInicial, precoFinal);
        preencherTabela(listaComputadores);
    }//GEN-LAST:event_txtValorIniCaretUpdate

    private void txtValorFinalCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtValorFinalCaretUpdate
        String nome = txtNome.getText();
        String marca = txtMarca.getText();
        String precoInicial = txtValorIni.getText();
        String precoFinal = txtValorFinal.getText();
        
        ComputadorDAO dao = new ComputadorDAO();
        
        List<Computador> listaComputadores = dao.listar(nome, marca, precoInicial, precoFinal);
        preencherTabela(listaComputadores);
    }//GEN-LAST:event_txtValorFinalCaretUpdate

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        ComputadorDAO dao = new ComputadorDAO();
        
        int itemSelecionado = tblItem.getSelectedRow();
        if(itemSelecionado != -1){
            int idItem = Integer.parseInt(tblItem.getValueAt(itemSelecionado, 0).toString());
            dao.ExcluirItem(idItem);
            JOptionPane.showMessageDialog(null, "Item excluído com sucesso.");
                    String nome = txtNome.getText();
            String marca = txtMarca.getText();
            String precoInicial = txtValorIni.getText();
            String precoFinal = txtValorFinal.getText();
            List<Computador> itens = dao.listar(nome, marca, precoInicial, precoFinal);
            preencherTabela(itens);
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um item para excluir.");
        }
>>>>>>> e9ad854 (Integração do banco de dados)
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void bntCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCadastrarActionPerformed
        CadastroItem telaCadastro = new CadastroItem();
        telaCadastro.setVisible(true);
        dispose();
    }//GEN-LAST:event_bntCadastrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
<<<<<<< HEAD
        int computadorSelecionado = tblComputadores.getSelectedRow();
        
        if(computadorSelecionado != -1){
        
        Administracao admin = new Administracao();
        Computador computadorEncontrado = admin.encontrarComputadorPorId(computadorSelecionado);
        
        EdicaoItem telaEdicaoItem = new EdicaoItem(computadorEncontrado, computadorSelecionado);
=======
        int computadorSelecionado = tblItem.getSelectedRow();
        
        if(computadorSelecionado != -1){
        int idComputador =Integer.parseInt(tblItem.getValueAt(computadorSelecionado, 0).toString());
        
        ComputadorDAO dao = new ComputadorDAO();
        Computador computadorEncontrado = dao.encontrarItem(idComputador);
        
        
        EdicaoItem telaEdicaoItem = new EdicaoItem(computadorEncontrado);
>>>>>>> e9ad854 (Integração do banco de dados)
        telaEdicaoItem.setVisible(true);
        dispose();
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Selecione um item para editar.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaPrincipalAdministracao telaAdmin = new TelaPrincipalAdministracao();
        telaAdmin.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
<<<<<<< HEAD
        //</editor-fold>
=======
>>>>>>> e9ad854 (Integração do banco de dados)

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioEstoque().setVisible(true);
            }
        });
    }
<<<<<<< HEAD
    
        public void atualizarLista(){
    if(!listaComputadores.isEmpty()){
        Computador computador;
        
        tableModel = new DefaultTableModel(tableColumns, 0);
        
        for(int i = 0; i < listaComputadores.size(); i++){
            computador = listaComputadores.get(i);
            
            String[] rowData = {computador.getNome(), computador.getMarca(), computador.getTipo(), String.valueOf(computador.getPreco()), String.valueOf(computador.getQuantidade())};
        
        tableModel.addRow(rowData);
        }
        
        tblComputadores.setModel(tableModel);    
    }
    else{
        tableModel = new DefaultTableModel(tableColumns, 0);
        tblComputadores.setModel(tableModel);
    }
}
=======
>>>>>>> e9ad854 (Integração do banco de dados)

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCadastrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
<<<<<<< HEAD
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblComputadores;
=======
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblItem;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtValorFinal;
    private javax.swing.JTextField txtValorIni;
>>>>>>> e9ad854 (Integração do banco de dados)
    // End of variables declaration//GEN-END:variables
}
