/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Services.VendaService;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import netbeans.Venda;

/**
 *
 * @author butuk
 */
public class RelatorioComprasAdministracao extends javax.swing.JFrame {
    
    public void preencherTabela(List<Venda> vendas){ //método para preencher a tabela com os dados salvos no banco.
        String colunas[] = {"Id", "Cliente", "Data", "Item", "Preço"}; //separa as colunas da tabela swing
        String dados[][] = new String[vendas.size()][colunas.length]; //separa as linhas da tabela swing de acordo com o tamanho da lista dada no parâmetro do método.
        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        int i = 0;
        for(Venda v : vendas){
            dados[i] = new String[]{ //a cada venda 'v', seus dados são coletados e preenchidos na linha da tabela swing.
                String.valueOf(v.getId()),
                v.getCliente().getNome(),
                v.getData().format(formatter),
                v.getComputador().getNome(),
                String.valueOf(v.getComputador().getPreco())
            }; 
            i++;
        }
        
        DefaultTableModel model = new DefaultTableModel(dados, colunas);
        tblVenda.setModel(model);
    }
    
    public RelatorioComprasAdministracao() {
        initComponents();
        VendaService service = new VendaService();
        
        preencherTabela(service.listarTodasVendas());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDataInicial = new javax.swing.JTextField();
        txtDataFinal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        bntExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVenda = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("System Select - Gerenciador de Vendas");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SYSYEM SELECT");

        jLabel2.setText("Pesquisar por data:");

        txtDataInicial.setToolTipText("Informe a data Inicial (ex: 10/02/2024)");
        txtDataInicial.setNextFocusableComponent(txtDataFinal);
        txtDataInicial.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtDataInicialCaretUpdate(evt);
            }
        });

        txtDataFinal.setToolTipText("Informe a data final (ex: 15/06/2024)");
        txtDataFinal.setNextFocusableComponent(btnPesquisar);
        txtDataFinal.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtDataFinalCaretUpdate(evt);
            }
        });

        jLabel3.setText("a");

        btnPesquisar.setBackground(new java.awt.Color(0, 102, 204));
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setToolTipText("Consultar todas as datas entre os intervalos informados");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnVoltar.setText("< Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(0, 102, 204));
        btnCadastrar.setText("Cadastrar Venda");
        btnCadastrar.setToolTipText("Cadastrar uma venda");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        bntExcluir.setBackground(new java.awt.Color(153, 0, 51));
        bntExcluir.setText("Excluir Venda");
        bntExcluir.setToolTipText("Excluir uma venda");
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar Venda");
        btnEditar.setToolTipText("Editar uma venda");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel4.setText("Gerenciador de Vendas");

        btnLimpar.setText("Limpar");
        btnLimpar.setToolTipText("Limpar filtros");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(bntExcluir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimpar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnVoltar)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(207, 207, 207)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(197, 197, 197)
                                        .addComponent(jLabel1)))))
                        .addContainerGap(147, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnVoltar))
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnPesquisar)
                    .addComponent(btnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(bntExcluir)
                    .addComponent(btnEditar)))
        );

        tblVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cliente", "Data", "Item", "Preço"
            }
        ));
        jScrollPane1.setViewportView(tblVenda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDataInicialCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDataInicialCaretUpdate

    }//GEN-LAST:event_txtDataInicialCaretUpdate

    private void txtDataFinalCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDataFinalCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataFinalCaretUpdate

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        
        VendaService service = new VendaService();
        List<Venda> vendas = service.listarTodasVendasDATA(txtDataInicial.getText(), txtDataFinal.getText()); //busca todos as vendas listadas no intervalo de tempo informado.
        
        if(vendas == null){
            JOptionPane.showMessageDialog(this, "Falha na busca, por favor informar no valor correto.(dd/MM/yyyy)"); //caso falha na busca entre o intervalo de tempo, este erro aparecerá.
        }
        else{
            preencherTabela(vendas);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaPrincipalAdministracao telaPrincipal = new TelaPrincipalAdministracao(); //abre a view TelaPrincipalAdministracao
        telaPrincipal.setVisible(true);
        dispose(); //e fecha a janela atual
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int vendaSelecionada = tblVenda.getSelectedRow();
        
        VendaService service = new VendaService();
        
        if(vendaSelecionada != -1){
            int idVenda = Integer.parseInt(tblVenda.getValueAt(vendaSelecionada, 0).toString()); //idVenda = ao número da linha selecionada
            
            Venda vendaEncontrada = service.encontrarVenda(idVenda);
            
            EdicaoVenda telaEdicao = new EdicaoVenda(vendaEncontrada); //abre a view EdicaoVenda com os dados encontrados da venda/linha selecionada
            telaEdicao.setVisible(true); 
            dispose(); //e fecha a janela atual
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Selecione uma venda para editar.");// caso nenhuma venda for selecionada e for apertado o botão de editar, aparecerá esse aviso
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
    CadastroVenda telaCadastro = new CadastroVenda(); //abre a view CadastroVenda
    telaCadastro.setVisible(true); 
    dispose(); //e fecha a janela atual
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
        VendaService service = new VendaService();
        int vendaSelecionada = tblVenda.getSelectedRow();
        if(vendaSelecionada != -1){
            int idVenda = Integer.parseInt(tblVenda.getValueAt(vendaSelecionada, 0).toString()); //idVenda = ao número da linha selecionada
            
            int confirmacao = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja excluir esta venda?", "Confirmação", JOptionPane.YES_NO_OPTION); //mensagem de confirmação se realmente deseja excluir a venda selecionado.
            
            if(confirmacao == JOptionPane.YES_OPTION){ //caso clicar em sim/yes, a venda será excluída
            service.excluirVenda(idVenda);
            JOptionPane.showMessageDialog(null, "Venda excluída com sucesso.");
            List<Venda> vendas = service.listarTodasVendas();
            preencherTabela(vendas);
            }
            else{
                JOptionPane.showMessageDialog(null, "Operação cancelada!"); //caso clicar em não/no, a operação será cancelada
            }   


        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione uma venda para excluir."); //caso for pressionado o botão de excluir e nenhuma venda for selecionada, esta mensagem aparecerá
        }
    }//GEN-LAST:event_bntExcluirActionPerformed
    
    
    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtDataInicial.setText(""); //limpa o campo de texto do filtro "data inicial"
        txtDataFinal.setText(""); //limpa o campo de texto do filtro "data final"
        VendaService service = new VendaService();
        List<Venda> vendas = service.listarTodasVendas();
        preencherTabela(vendas); //preenche a tabela com todas as vendas, sem filtro
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioComprasUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioComprasUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioComprasUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioComprasUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioComprasUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVenda;
    private javax.swing.JTextField txtDataFinal;
    private javax.swing.JTextField txtDataInicial;
    // End of variables declaration//GEN-END:variables
}
